[package]
name = "nest_climb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
touch_controls = []

[dependencies]
bevy = { version = "0.10.1" }
bevy_ecs_ldtk = { version = "0.7.0", features = ["atlas"] }
bevy-tnua = { version = "0.7.0", features = ["rapier_2d", "bevy_rapier2d"] }
bevy_asset_loader = { version = "0.16.0", features = ["2d"] }
bevy_rapier2d = { version = "0.21.0", features = [
	"simd-stable",
	"debug-render-2d",
] }
leafwing-input-manager = "0.9.2"
seldom_fn_plugin = "0.3.0"
# smooth-bevy-cameras = "0.8.0"
bevy_egui = "0.20.3"

# bevy-ui-navigation = { version = "0.24.0", path = "C:/Users/vince/Documents/dev/Forks/bevy_ui_navigation" }
bevy-ui-navigation = { version = "0.24.0", git = "https://github.com/VincentDouchin/ui-navigation.git" }
bevy_pkv = "0.7.0"
bevy_mod_ui_texture_atlas_image = "0.4.1"

# bevy-parallax = { git = "https://github.com/VincentDouchin/bevy-parallax.git" }
bevy_ninepatch = "0.10.0"
bevy_easings = "0.10.0"
[target.'cfg(target_arch = "wasm32")'.dependencies]
bevy = { version = "0.10.1" }
[target.'cfg(target_arch = "windows")'.dependencies]
bevy = { version = "0.10.1", features = ["dynamic_linking"] }

[profile.dev.package."*"]
opt-level = 3

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
