[package]
name = "nest_climb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
bevy = { version = "0.10.1" }
bevy-tnua = { version = "0.3.0", features = ["rapier_2d", "bevy_rapier2d"] }
bevy_asset_loader = { version = "0.16.0", features = ["2d"] }
bevy_rapier2d = { version = "0.21.0", features = [
	"simd-stable",
	"debug-render-2d",
] }
leafwing-input-manager = "0.9.2"
seldom_fn_plugin = "0.3.0"
smooth-bevy-cameras = "0.8.0"

[target.'cfg(target_arch = "wasm32-unknown-unknown")'.dependencies]
bevy = { version = "0.10.1" }

[profile.dev.package."*"]
opt-level = 3
